### ISSUE TITLE
Symbol instance context key is not being updated after a sync

### ISSUE THREAD

**Issue by ziyafenn** [contentsync/SketchContentSync#113]
Hello, I once emailed you about this problem, but I believe it still remains unresolved. 

On the v6.5.1, symbol instance overrides (all of them) do not appear on the google spreadsheet. Is there any plans to fix this issue? Otherwise, it is impossible to fully utilize the symbol swapping feature.

Thanks.

**Comment by ziyafenn** [comment]
Update, symbol type works just fine, but context is not being overwritten. Renaming the layer also doesn't help. So it always takes the origin symbol instance name.

**Comment by dbrody** [comment]
Thank you for comment, we will investigate.

**Comment by dbrody** [comment]
@ziyafenn - The new release 6.5.5 addresses and fixes this issue. Thank you for filing the issue!
