### ISSUE TITLE
Layer can't be deselected after update

### ISSUE THREAD

**Issue by ziyafenn** [contentsync/SketchContentSync#114]
On the latest Sketch 62, after selecting a layer/symbol and updating its keys, they remain selected and i need to reopen the file to continue working. Otherize it's just impossible to deselect them.

**Comment by dbrody** [comment]
Thank you for the issue submissions. We are aware of this issue and working on updates to fix it.

**Comment by dbrody** [comment]
Hi @ziyafenn , This has been fixed in release 6.5.2.
