### ISSUE TITLE
Support nested symbols

### ISSUE THREAD

**Issue by hanonno** [contentsync/SketchContentSync#12]
Really like the new symbols support, the only thing I'm missing is support for nested symbols.

For example:
- I have a row with an avatar, name and job title
- If I select them and create a symbol the overrides work as advertised
- If I make a symbol out of the title and job title labels they don't get synced anymore

**Comment by dbrody** [comment]
OK, this is in the pipeline. I am seeing some strange behavior with the SketchAPI on retaining any SubSymbol overrides (i.e. if a subsymbol is swapped out for another one via overrides).

I've been able to make some progress on updating text of sub symbols but I am awaiting some dev input from Sketch dev maillinglist before this feature is fully implemented.

Once this feature is added, I can see some awesome new abilities for ContentSync :)

👍  @hanonno

**Comment by contentsync** [comment]
@hanonno 

Exciting news: Version 2.0.1 now supports nested symbol and nested symbol overrides.

For now, check out the details in this comment:
https://github.com/contentsync/SketchContentSync/issues/29#issuecomment-286934512

**Comment by contentsync** [comment]
We are considering this issue closed. If you do run into more issues, please open a new issue.

Thank you again for using ContentSync!
