### ISSUE TITLE
Exception thrown with Sketch 96 beta

### ISSUE THREAD

**Issue by SheffieldKevin** [contentsync/SketchContentSync#140]
Sketch is seeing exceptions like the following being thrown in the current Sketch 96 beta.

This selector has been removed from the class and is no longer used to make the behaviour consistent over the inspector. We believe you can just remove calling this method.

We will be blocking plugin version `"com.syncify.sketch.contentsync" : "8.6.3"` as incompatible with Sketch 96.

```
NSInvalidArgumentException: -[MSCollapsibleHeaderInspectorItem setConstrainActiveButtonAreaToImage:]: unrecognized selector sent to instance 0x7f87b32e8d40

0  CoreFoundation +0xf83db      __exceptionPreprocess
1  libobjc.A.dylib +0x15e22     objc_exception_throw
2  CoreFoundation +0x18f528     -[NSObject(NSObject) __retain_OA]
3  CoreFoundation +0x62628      ___forwarding___
4  CoreFoundation +0x62064      _CF_forwarding_prep_0
5  ContentSyncRealtime +0x41c46 -[CSContentKeyInspectorSection2 createItems]
6  ContentSyncRealtime +0x40c48 -[CSContentKeyInspectorSection2 init]
7  ContentSyncRealtime +0x484ee -[CSSwizzler(MSStandardInspectorViewControllers) contentSyncViewController]
8  ContentSyncRealtime +0x48426 __Swizzle_viewControllers
9  Sketch Beta +0x572b68        -[MSNormalInspector initWithInspectors:parent:] (MSNormalInspector.m:68:48)
```

**Comment by dbrody** [comment]
We are reviewing this issue and working on an update.

**Comment by dbrody** [comment]
@SheffieldKevin Thank you for the detailed bug report. This been resolved in release 8.6.5.

**Comment by dbrody** [comment]
@SheffieldKevin Are you able to confirm and unblock the plugin as incompatible?

**Comment by SheffieldKevin** [comment]
I only blocked up to version `8.6.3`

**Comment by dbrody** [comment]
Great I will close this issue.

**Comment by SheffieldKevin** [comment]
I will keep an eye out in our crash and exception reporter if I see anything from content sync and let you know if I see reports with a later version number of your plugin.
