### ISSUE TITLE
Symbols Not Syncing

### ISSUE THREAD

**Issue by nmarketti** [contentsync/SketchContentSync#29]
Opened up ContentSync today to an update. Updated to latest and it noticed that Symbols were not syncing.

All other content was syncing fine, but anything that was a Symbol would not sync.

**Comment by contentsync** [comment]
@nmarketti Thank you for the note. We are looking into it right now.

For now, you can try to push a new version to grab the new symbol keys. Our update did make symbol and nested symbol names a bit more strict to force adding context to a variable.

We will look into fixing this and get a patch version soon. Let us know if pushing a content version and using those keys could be a viable solution for you.

Sorry for the inconvenience, we will keep this issue updated!

**Comment by contentsync** [comment]
@nmarketti 

Version 2.0.1 of SketchContentSync is now released and includes a patch to fix this. To install, go into your settings on ContentSync.app, uninstall and then reinstall ContentSync for Sketch. You should see Version 2.0.1 below it afterwards.

This version supports much better nested symbol and override support.

If you have:
+ Symbol Master `Symbol1` with a text field `TextField`
+ Symbol Master `Symbol2` with `SubSymbol` symbol instance of `Symbol1`
+ Symbol Instance `Instance 1` of `Symbol1` on an Artboard
+ Symbol Instance `Instance 2` of `Symbol2` on an Artboard

Then the keys would do the following:

+ **`TextField[Symbol1]`**, **`TextField[default]`** or **`TextField`** will set the value of the actual text of `TextField` within the `Symbol1` master symbol.
+ **`TextField[Symbol2][SubSymbol]`** will set the override value of `TextField` on the `SubSymbol` instance within `Symbol2` 
+ **`TextField[Instance 1]`** will set the override of `TextField` on `Instance 1` 
+ **`TextField[Instance 2][SubSymbol]`** will set the override of `TextField` of the `SubSymbol` on `Instance 2`

When syncing a version, if the key is not present it will clear out an override. So make sure to push a working version before pulling a previous one to save the updates.

Let us know if this is confusing and we can clarify as needed.

Also, let us know if you continue to have problems or if it is fixed so we can close this issue.

Again, thank you for using ContentSync!

**Comment by nmarketti** [comment]
Yeah, I think I'm confused on this.

I have a symbol named "Global / Transparent Nav".

Inside that symbol I have five nav text layers.

navOne
navtwo
...
...
...

After the fix they stopped syncing from your doc.

If I want to push, I have to exclude another 200+ keys that are already set in the document, which is not viable for me to go through and "push" to update values.

Is there a simple way to just update the key names for this to continue to sync correctly?

**Comment by nmarketti** [comment]
**Update:**

First off, apologies for so the long responses and all. I'm mid-project and this was just causing a hassle as we're under some tough deadlines. I think I figured this out.

What resolved this is adding "[default]", to the end of each key. 

I'm not sure having to add "[default]" to the end of the master makes sense in my opinion. But maybe some more use and it might make sense. As long as the key matched in the symbol, I feel it should update. And if I want to override, then I use navOne[SubSymbol] 

I think the biggest struggle I'm having is "pushing" content. While great in theory, it doesn't work effectively in a way that makes the workflow quicker from what I've found mid project. 

If I try to push currently, it pushes many keys that make no sense and aren't usable. An example is "hex" colors on a separate board. It will effectively update pre-set keys which is great, but mid project as things get added/removed, manually doing settings keys and organizing them on the doc makes for better organization. 

I could be using this completely wrong, but from my uses that's what I've experienced.

**Comment by contentsync** [comment]
@nmarketti 

First, thank you for using ContentSync and for working with us as we help update and extend the product. We are definitely getting processes in place to make sure that as we make more and larger updates, it continues to work with previous versions.

That said, I apologize for the headache on this one. I understand how project deadlines are and how it would be frustrating for this to impact that. We seriously do appreciate your input, comments, and patience.

Yes, adding the "[default]" should help as that is what will impact a Master Symbol unless the name of the symbol is given explicitly.

The current largest issue we have (which we are working on) is that **duplicate layer names will all be treated as the same content.** This is an issue as designs evolve and expand and designers copy and paste layers. We are working on an update which will solve for that and work independently of the actual layer name. However, that is still probably a few weeks out (hopefully at most). You can read more here: https://github.com/contentsync/SketchContentSync/issues/30 We welcome any comments or ideas or input you may have.

**Comment by nmarketti** [comment]
Everything is all good now! And it's been noted in my workflow moving forward.

Thanks for your help on this and we're looking forward to see this evolve!

😄 

Cheers,
Nolan

**Comment by contentsync** [comment]
Great to hear! Thank you for using ContentSync and for making us part of your flow.

More exciting stuff is on the way!
