### ISSUE TITLE
[Feature Request] Integrate with Sketchpacks Relay to serve auto-updates

### ISSUE THREAD

**Issue by adamkirkwood** [contentsync/SketchContentSync#31]
More details found @ https://github.com/integration/sketchpacks-relay

Example
![screen shot 2017-03-22 at 4 08 57 pm](https://cloud.githubusercontent.com/assets/52746/24224720/fc40de64-0f19-11e7-8473-a2798193fc33.png)

**Comment by contentsync** [comment]
@adamkirkwood Yes, we will definitely look into that. Looks like there is a bit of a challenge since our plugin is a subfolder / zip file within our repo. We will look into it more.

**Comment by contentsync** [comment]
@adamkirkwood Also, our ContentSync.app application makes it very easy to install / update the plugin as a workaround for now.

**Comment by dbrody** [comment]
As of V2.2.1 SketchContentSync now supports Sketchpacks!

Thank you for the request @adamkirkwood !
