### ISSUE TITLE
Allow 'Share Values Across Common Names'

### ISSUE THREAD

**Issue by dbrody** [contentsync/SketchContentSync#38]
### Current Limitation
Currently, when the **'Include Layer Context Details'** is toggled, it prevents multiple text layers from using the same values.

### Proposed Solution
This is to add another settings option to **'Share Values Across Common Names'**. This would allow a single entry on google documents to have multiple paths which would allow for having multiple layers share one entry.

### Given
Two artboards `artboard1` and `artboard2` both with a text layer named `text`.

#### With this feature toggle **ON**: 
One row would be created on google documents with the path cell of value with multiple lines:

| Object ID  | Path | Key |
| ------------- | ------------- | ------------- |
| objectID1<BR/>objectID2 | artboard1.text <BR/> artboard2.text | Key |

Both of the text fields would always sync with the same data on a pull.

#### With this feature toggle **OFF**: 
Two rows would be created on google documents with  a single path per entry:

| Object ID  | Path | Key |
| ------------- | ------------- | ------------- |
| objectID1 | artboard1.text  | Key1 |
| objectID2 | artboard2.text  | Key2 |

Each text layer could have different values on a pull.

**Comment by markgrahamdunn** [comment]
Hi @dbrody, how soon will this feature be implemented?

**Comment by dbrody** [comment]
@markgrahamdunn  ContentSync 6 now supports this by using custom content key overrides. While layers default to their layer name, you can now override their content key in the ContentSync layer inspector.

The inspector looks like this:
![screen shot 2019-02-14 at 12 45 21 pm](https://user-images.githubusercontent.com/210322/52816594-7a60dd80-3056-11e9-913e-10cff8a39fd2.png)

Now you can override with custom keys and/or custom sheet:
![screen shot 2019-02-14 at 12 45 39 pm](https://user-images.githubusercontent.com/210322/52816611-8351af00-3056-11e9-846c-1ae5e11e1d54.png)
