### ISSUE TITLE
Non-Latin character set styles 

### ISSUE THREAD

**Issue by Joshuwar** [contentsync/SketchContentSync#4]
Great project. This isn't so much an issue as encouragement: 

I'm currently doing lot of work with Chinese/English designs, and you generally need to use different fonts (and font sizes, weights, spacing, line height, etc) to make typography look good with non-Latin character sets.

So whilst this plugin makes it easy to collate translations and add them to a sketch file, when working with non-Latin alphabets a designer will still need to do an amount of manual tweaking to optimise the design.

**Comment by dbrody** [comment]
Awesome, thank you a ton for the feedback and the encouragement.

We definitely saw a nice use for this plugin when working with English, Spanish and Korean but Chinese is a completely difference design constraint. Would love to hear more details on your use case and see how we may be able to add features that would make your life easier. Any ideas, comments, or knowledge shares would be more than welcome here.

Thanks again for the feedback!

**Comment by dbrody** [comment]
As a start how about this:

Would it be helpful to be able to set the text alignment along with the copy per language / version?

**Comment by Joshuwar** [comment]
Hey, thanks for the replies.

Here's a quick made up example of the kind of thing I'm talking about:
![text variations](https://cloud.githubusercontent.com/assets/610938/17722582/d9306e44-6465-11e6-86f0-bc6eaf9d73df.png)
If I were to leave the type styles the same in both English and Chinese, one language or the other would have to be less readable, less stylish. 

A related point is that if you try to write in Chinese characters using a font that does not contain them, the font is automatically substituted for the OS's best guess of an equivalent Chinese font (eg. 'hand-written' style Chinese fonts tend to replace Latin serif/cursive scripts, while cleaner, smoother Chinese fonts replace Latin sans fonts). Needless to say, these defaults often need to be overridden in the name of typographic decency.

On your suggestion about setting alignment per copy version, how do you think you could implement that? See, I love the simplicity and flexibility of the system you've designed so far- and I worry that adding further config at the spreadsheet end could detract from this. And as you can probably see from my example image, alignment is only one aspect of the problem.

I have a feeling that the most elegant way to get around the issue might leverage some part of Sketch's existing text-style system, but I'm not sure how, exactly. Quite possibly beyond the scope of this particular project, however...

Anyway thanks again for all your work, and please let me know if there's any way I can help at all.

**Comment by dbrody** [comment]
@Joshuwar Thank you very much for your detailed response. Sounds like a great build on the use cases this plugin is meant to support. I like your suggestion of supporting a Sketch text-style per copy version could be a great solution. 👍

**Comment by shinhwaxoxo** [comment]
Hey guys,

I found this plugin by accident actually and it's got great potential.

I'm currently working on an Asian designs too (Japanese >< English), and having the same issue. The only plugin I've seen so far that can do what we want in regards of different sizes etc is this one by Qordroba: https://github.com/Qordobacode/qordoba-for-sketch.

They're no longer working on the plugin I don't think, but basically how they do it is by creating each language a separate stylesheets like you mentioned @dbrody 

Right now I'm using Google's translation toolkit, however it's not designed for designers who use Sketch. 

I'm looking forward to seeing more updates with this plugin!

**Comment by dbrody** [comment]
@shinhwaxoxo @Joshuwar 

I'm excited to say that a first step in the direction of this issue's conversation is now live - check out V2.1.0.

This version will synchronize these properties of a text layer to google documents:

- Font (size, family, weight)
- Style (bold, italic, underline, and strikethrough)
- Font Color

It will work even if a single Text Layer in Sketch has multiple different font stylings.

Future iterations will include text alignment, character spacing and more!

**Comment by dbrody** [comment]
@shinhwaxoxo @Joshuwar I'm going to close this because of lack of activity. Check the plugin for all the updates since the time of this issue and file new ones for anything else that comes up.

Thanks again for all the input!
