### ISSUE TITLE
Allow for automatic translations

### ISSUE THREAD

**Issue by dbrody** [contentsync/SketchContentSync#46]
# Request
Make it easy to translate a design with minimal effort. Using Google translation services, add the ability to translate a design.

# Details
+ Specify source / destination languages
+ Create new version automatically with the translated content

**Comment by markgrahamdunn** [comment]
this can somewhat be done in google sheets itself.
![cwnrzfpueaa-lrp mp4](https://user-images.githubusercontent.com/1683184/31444359-53a98152-ae9c-11e7-8d2a-99e07a201569.gif)

**Comment by dbrody** [comment]
Yes it can. Doing it in Google Spreadsheets is great for now!
