### ISSUE TITLE
Ability to override Symbols

### ISSUE THREAD

**Issue by MattCowBoy** [contentsync/SketchContentSync#55]
# Request

Hi @dbrody, you did an awesome plugin.
It  would be great have the possibility to override symbols and push in Google Sheet their content so copywriter can update them.

Is it feasible?
Thank you so much

**Comment by dbrody** [comment]
Hi and thank you. Symbols and overrides are supported in the plugin. There may be some useful details here #29 . Can you provide some additional details so I can help debug it more accurately?

**Comment by MattCowBoy** [comment]
I've noticed that, if I write manually in the Google Sheet following the syntax "textField[symbol]", even for nested symbols, the plugin works perfectly when pulling content from Google Sheet. The push doesn't work. I can't upload symbols value in the Google Sheet.

In addition, do you know if is it possible ignore the font-size in Google Sheet? It would be awesome if I can import with style ignoring the font-size, because I can use the same content on different breakpoints, using the orginal font-size given in the artboard in Sketch.
…

**Comment by dbrody** [comment]
Hi @MattCowBoy,

We will look in to this. Do you have anything special in your file such as special characters, sub-symbol instance overrides, etc?

Thanks,
David

**Comment by MattCowBoy** [comment]
Nothing special. Just some sub-symbol instance overrides, but you said that they are supported.

**Comment by dbrody** [comment]
Are you pushing a full file or do you have specific layers selected when pushing?

**Comment by contentsync** [comment]
@MattCowBoy Please try the new release version 3.0.2. We have fixed some issues with partial push/pulling. Perhaps this will solve your issue. If not - we will continue to look into it.

Thanks!

**Comment by dbrody** [comment]
Hey @MattCowBoy, have you had a chance to try again with the most recent version? It would be great to get some activity on this issue and identify the possible issue.

Also, as for:
> In addition, do you know if is it possible ignore the font-size in Google Sheet? It would be awesome if I can import with style ignoring the font-size, because I can use the same content on different breakpoints, using the orginal font-size given in the artboard in Sketch.

It would be great if you could file a separate issue / feature request for that with a little more color.

**Comment by MattCowBoy** [comment]
Hey David
I've downloaded the last version from GitHub and from the website and it
does not work. The ContentSync panel on the left has gone and, even
clicking on toggle panel in the menu, I can't see it.



Il giorno sab 26 ago 2017 alle ore 21:58 David Brody <
notifications@github.com> ha scritto:

**Comment by dbrody** [comment]
If you open up the Sketch Plugins Panel, what do you see regarding ContentSync?

Also, within the plugins panel, if you click on the gear icon then click Reveal Plugins Folder, what do you see regarding ContentSync?

**Comment by MattCowBoy** [comment]
Hey David, now I can see the ContentSync Panel and everything works fine,
except for symbols. I can see in the spreadsheet only the Symbol sheet, but
in the sheet related to one page I haven't any text if these are in symbols.


Il giorno mar 29 ago 2017 alle ore 16:35 David Brody <
notifications@github.com> ha scritto:

**Comment by dbrody** [comment]
Hey Matteo,

We released some updates in 3.0.05 as well as some server updates since your comment. Is this still an issue for you?

**Comment by MattCowBoy** [comment]
Hey David,
now Symbols work but not nested ones don't. To update nested symbols I have to create row in spreadsheet with []syntax.

**Comment by dbrody** [comment]
@MattCowBoy Yes, currently symbol overrides that are blank are not created automatically. Only entries with overrides are created.

Were you hoping to have all the symbol override options automatically created in the google sheet?

**Comment by dbrody** [comment]
@MattCowBoy - Check out version 4.2 #72 - It allows much greater flexibility and will push all of these by default. I'm closing this issue for now - but please create a new issue with any follow up items.
