### ISSUE TITLE
ContentSync Plugin pane gone after 3.0.4 update

### ISSUE THREAD

**Issue by imsirfing** [contentsync/SketchContentSync#62]
Two issues:
1) I was using the old version of the plugin, and it stoped syncing... It was working intermittently, but now won't sync at all. In my account, it registers that the sync has gone through (https://www.contentsync.io/simonesept/gmb_master_redacted_aug11_l10n_final-sketch/activity), but the copy in the file isn't updating. I noticed that my plugin had an update pending, so I updated it, which led to:

2) In sketch, the plugin pane on the far left where the upload/download buttons were is missing. The plugin is still showing as installed, and I've tried to Toggle it to make it appear, but it's not there.

Things I've tried:
- using a different version of the sketch file linked to the same google sheet
- uninstalling the plugin and reinstalling
- uninstalling sketch entirely and reinstalling sketch and then the plugin

Help please!

Sketch Username: simonesept
Sketch filename: GMB_MASTER_REDACTED_Aug28_L10n_final_V6.sketch

**Comment by dbrody** [comment]
@imsirfing 

We are looking into that now.

As a first step - can you check the Sketch plugins folder (In Sketch, `Plugins` > `Manage Plugins...` then click on the gear icon and then `Reveal Plugins Folder`). Please make sure ContentSync is at `SketchContentSync.sketchplugin` and not something like `SketchContentSync 2.sketchplugin` or the like. What name do you see?

**Comment by dbrody** [comment]
@imsirfing 

We have also just released version 3.0.5 which we think may be another solution. It removes a framework signature on the plugin which seems to be causing issues.

Please let us know here how that new version behaves on your system. Hopefully that fixes things.

**Comment by ssept** [comment]
Hi @dbrody—I was also experiencing these issues—just installed version 3.0.5, which brought back the pane on the left, but still having trouble syncing.

**Comment by dbrody** [comment]
@ssept - Good to hear pane is back, perhaps try logging out then back in. It may be a Keychain issue we will have to look in to next.

**Comment by ssept** [comment]
@dbrody, I logged out and back in, and one sync worked! Tried syncing again and it stopped working, even after repeating the login process.

**Comment by dbrody** [comment]
@ssept Interesting, we do see a couple syncs coming from you account over the last few minutes. 

One thing to note - selected layer syncs may seem like a sync is not working when it is pushing/pulling only the selected layers instead. That feature is not currently as obvious as it could be so perhaps that could be part of it?

**Comment by imsirfing** [comment]
Agreed pane is back, haven't been able to sync yet though (note that @ssept and I are using the same login and troubleshooting on the same file).

I've been able to swap to some of the languages in our spreadsheet, but some of them aren't working. Is there a way to error check why a given sync isn't working?

**Comment by imsirfing** [comment]
I was able to sync the columns called Belarus, Algeria (ar), Denmark, but not Ireland, Finland, Sweden, Norway (which, annoyingly, are the ones we need tonight).

Not sure about the selected layer syncs, because we're not doing anything different between syncs for the ones which are working and the ones which aren't. Could there be something in those columns in our spreadsheet that's making it fail? We don't see anything obvious...

**Comment by dbrody** [comment]
@imsirfing - We don't see any errors being recorded on your syncs right now. Are there any special characters in those columns compared to others? Using selected layers could help pinpoint if it is a syncing issue or a content issue. If some specific layer is causing the issue, a selected layer sync could work around that.

**Comment by dbrody** [comment]
We dont see any errors on our server side. This means the issues may be related to something local within the Plugin / Sketch. I see most of your requests are Pull. Is push working for you if you try another file / project?

**Comment by imsirfing** [comment]
Thanks David, we'll take a look through this again in the morning to see if
there are odd characters going on.


- James Tinsley

**Comment by dbrody** [comment]
@imsirfing - Just checking in for any update to keep up to date with your issue. It looks like you have been syncing ok over the past few hours. Any update?

**Comment by ssept** [comment]
Hi @dbrody, thanks for checking in! I have been syncing—sometimes successfully and others unsuccessfully... also have checked the sheet for any odd characters, but not seeing anything. It's strange because Austria worked, but Switzerland did not (both in German). 

Could there be anything else going on?

**Comment by imsirfing** [comment]
Agreed, it's still only working for some and not others. I looked through the data comparing Denmark (syncing) to Finland (not-syncing), and I can't see any obvious differences. Both have a number of odd characters because of the language.

Anything else we can do to troubleshoot?

**Comment by dbrody** [comment]
@imsirfing @ssept - Interesting we do see two notes here.

1) Version Naming
Im seeing that:
+ version name `Austria` worked
+ version name `Switzerland (fr)` did not work

Perhaps the name itself is cuasing issues. We can look futher into that soon. Perhaps try to remove the ` (fr)`?

2) Version Length Issues
It looks like some of your push/pulls have lots of data? We do actually see a pull issue on the Google docs range right now. Can I ask what Google Docs ranges you are using for all of your data? Perhaps our pull is not set up to use double letter columns or something of the like.

**Comment by ssept** [comment]
Hi @dbrody—

We did have success with columns such as Malaysia (en), India (hi), etc. but  it seems like option 2 might be the case! All of the ones that have worked are in double letter columns. 

Is that something that can be set up, or should I move them into single letter columns?

**Comment by dbrody** [comment]
@ssept - We've released a patch on the server which should fix this issue. Content Versions on multi-letter columns should now work as expected. Thanks for your patience with this issue.

I'm closing this ticket as it is around the missing left pane which is now working.

If you do experience any other issues, continue filing issues here and we will look in to them.

Thanks for using ContentSync and helping to make it better!

**Comment by imsirfing** [comment]
This seems to have solved the issue! Thank you so much for your support!

**Comment by dbrody** [comment]
Our pleasure. Please help spread the word and share ContentSync with your friends.
