### ISSUE TITLE
Ability to disable font size when pulling from Google Sheet

### ISSUE THREAD

**Issue by MattCowBoy** [contentsync/SketchContentSync#66]
It would be awesome if allow to disable only specific font properties.

I used ContentSync most for responsive project, and the ability to use a single source (Google Sheet) for several target would be awesome. It could be done using the same layer name. In this way, when pulling a new version from Google Sheet it will update all layers with that name. It's important (for responsive projects) to don't consider the font size when pulling (because in mobile views font size are maybe smaller than the desktop ones). For this reason I suggest to let users choose what font properties disable (ex. font-size, color, all of them).

Do you think that it will be possible?

Thank you

**Comment by dbrody** [comment]
@MattCowBoy - Sounds like a useful feature. We will see how we can work this into the next release. Thanks!

**Comment by dbrody** [comment]
@MattCowBoy - Are you hoping for global settings across all versions or would you want specific settings per version?

We're also looking into if these settings should be captured locally per user or globally per project on the remote server.

**Comment by dbrody** [comment]
@MattCowBoy - ContentSync 6 now supports this.

Text layers allow you to choose which properties to sync now:
![sketch-interface-layers-text](https://user-images.githubusercontent.com/210322/52816327-dc6d1300-3055-11e9-914d-da0ca22a34d8.png)
