### ISSUE TITLE
Impossible to manage ContentSync projects

### ISSUE THREAD

**Issue by simonbrtrnd** [contentsync/SketchContentSync#69]
Hi @dbrody ,

Thanks for this awesome plugin.
I am trying to work on several projects in the same time. I can create different projects but I can't switch from one project to an other.
The "Projects" settings doesn't work. The display is buggy, please see the image below.

![image](https://user-images.githubusercontent.com/20772024/40412011-65589a56-5e72-11e8-8e4b-22bcc3179d53.png)

**Comment by dbrody** [comment]
@simonbrtrnd - Thank you for the note. Glad you are enjoying the plugin.

We have seen this issue before and are working to address it.

Can you provide your MacOS, Sketch, and ContentSync versions?

**Comment by simonbrtrnd** [comment]
@dbrody - Thank you for merging my accounts.

I hope you will find the solution. Good Luck :)

**Comment by simonbrtrnd** [comment]
@dbrody - Just to let you know that I have updated my MacOS to High Sierra 10.13.4 and there is no more issue.

**Comment by dbrody** [comment]
@simonbrtrnd - Our newest release (4.1) now includes some updates which should help fix this issue. Please report back if you continue to see it.

Marking this issue as closed for now.
