### ISSUE TITLE
Error on push [MSImmutableTextLayer ancestors]

### ISSUE THREAD

**Issue by lmjabreu** [contentsync/SketchContentSync#74]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/40119971/42284214-b9934a24-7fa3-11e8-92f7-87abc41d72f0.png">

I'm getting various errors when trying to sync after the recent update (4.2). Happens on 4.2.x as I'm currently running 4.2.1 version of the plugin. Let me know if I need to specify any other detail to help debug this.

**Comment by lmjabreu** [comment]
Worked on a separate file after copying a symbol from the original one over to it and selecting that symbol instance. Doesn't work if I clear the selection on both old and new document.

**Comment by dbrody** [comment]
@lmjabreu - [Version 4.2.2](https://github.com/contentsync/SketchContentSync/releases/tag/4.2.2) updates some items which may help with this issue.

Any additional details you can give if you see it again would help tremendously. Thanks!

**Comment by dbrody** [comment]
@lmjabreu - Thanks for providing that!

**Comment by dbrody** [comment]
@lmjabreu - I created the issue #77 in follow up to some of your comments. I'm going to close this issue since it seems resolved and we can follow up with additional issues as they come up.
