### ISSUE TITLE
Manifest version not updated in latest 4.2.3

### ISSUE THREAD

**Issue by lmjabreu** [contentsync/SketchContentSync#79]
I'm assuming the manifest is generated from plugin.js: 
https://github.com/contentsync/SketchContentSync/blob/master/SketchContentSync.sketchplugin/Contents/Sketch/plugin.js#L355

s/version: '4.2.2'/version: '4.2.3'

**Comment by dbrody** [comment]
@lmjabreu - Good catch. Fixed with version bump 4.2.4.
