### ISSUE TITLE
Possibility to exclude certain lists (versions) from syncing

### ISSUE THREAD

**Issue by markgrahamdunn** [contentsync/SketchContentSync#85]
Would it be possible to exclude certain lists (versions) from syncing?
Atm we have different stakeholders adding flow structure / comments in columns which are irrelevant for syncing values.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/1683184/43734040-ca3e7e7a-99b6-11e8-8c66-19f37016696f.png">

**Comment by dbrody** [comment]
@markgrahamdunn - seems like a very reasonable request. Any suggestions as to how you would like to denote which versions should not be synced?

**Comment by markgrahamdunn** [comment]
would adding a checkbox in the Project Versions be feasible?

![image](https://user-images.githubusercontent.com/1683184/43777225-6cf72bda-9a52-11e8-9f67-c98ef4f06d2a.png)

**Comment by dbrody** [comment]
@markgrahamdunn - You can now select which versions to allow syncing on in the ContentSync platform. Go to your project then choose "Versions" under the More dropdown in the top right. You can then select which versions you'd like to enable/disable syncing on.
