### ISSUE TITLE
Ability to edit the project name

### ISSUE THREAD

**Issue by markgrahamdunn** [contentsync/SketchContentSync#86]
Could it be possible to edit / change the Project name in contentsync project settings.
Occasionally we start with a dummy project and give it a less thoughtful name.

![image](https://user-images.githubusercontent.com/1683184/44214784-38bbac80-a171-11e8-8a08-0f8f19c4c050.png)

**Comment by dbrody** [comment]
Yep, we will add that in the next iteration on the platform.

**Comment by dbrody** [comment]
@markgrahamdunn - You can now edit the project name on the ContentSync platform. Just go into the project view, select "Settings" in the more dropdown in the top right, and you can then edit the project name. You will need to reselect the right project in the Sketch plugin afterwards.
