### ISSUE TITLE
ID appears in the spreadsheet?

### ISSUE THREAD

**Issue by virgils** [contentsync/SketchContentSync#88]
Any idea why the ID would show up underneath the label?

![screen shot 2018-09-05 at 2 37 27 pm](https://user-images.githubusercontent.com/438088/45113791-4e414800-b119-11e8-9522-fd54efd6d8b9.png)

**Comment by dbrody** [comment]
This is a feature to allow each layer to be unique in the spreadsheet.

You can configure how layers are transformed into keys using the "*Key Transform Function*" under the Project Preferences -> Functions tab:
![screen shot 2018-09-05 at 11 45 07 am](https://user-images.githubusercontent.com/210322/45114229-51c8d500-b101-11e8-8ffb-6edcc202a430.png)

The default of "Unique per Layer Context -> Name" includes the layer ID. You can remove it by using the option "Context -> Name". To change, choose the option in the dropdown on the top right, then press save in the bottom right.

**Comment by virgils** [comment]
Great perfect! Thank you so much for the quick reply!
