### ISSUE TITLE
Sheet per Page not working?

### ISSUE THREAD

**Issue by virgils** [contentsync/SketchContentSync#89]
I enabled the Sheet per Page but that doesn't seem to work. Also tried to create different versions.

The different pages are merged to one sheet. For example I have a title at two different pages;

![screen shot 2018-09-05 at 2 37 27 pm](https://user-images.githubusercontent.com/438088/45113888-93657a00-b119-11e8-8081-57576da782e2.png)

**Comment by virgils** [comment]
I actually see the tooltip now. But the document is set to private, not public.

![screen shot 2018-09-05 at 2 48 14 pm](https://user-images.githubusercontent.com/438088/45114355-c9572e00-b11a-11e8-905e-2d44064a1023.png)

**Comment by dbrody** [comment]
Actually, it has been changed. See #84 

An upcoming release will update the plugin / platform UI to fix this.

**Comment by dbrody** [comment]
This is now done using the *Sheet Transform Function* for additional flexibility.

**Comment by virgils** [comment]
Would it be possible if two pages over two sheets containing the same keyname, that when pulling it would grab the last keyname it would find and apply is for both pages. 

So for example the Title for from my Contactpage Sheet (I also have a Homepage Sheet) is being applied to my Homepage Sketch board Title.

**Comment by dbrody** [comment]
Thanks @virgils !

By default when pulling it will do the following and use the value from the first key found:
- Look for the layer's key on the layer's sheet
- Look for the layer's key on any sheet

However, when pushing, if the same key is already found on another sheet, it will not create a new key.

You should be able to manually create the key "Title" on both sheets, under the same version and then when pushing / pulling it should do as you'd like. I'd have to dig in deeper to verify all of this, but that will have to wait a bit at the moment. 

Hope that helps!

**Comment by virgils** [comment]
Ah yes, pushing works. Pulling overwrites the wrong common title field in the Sketch file. I'll wait for the updates, thanks again for the great work already!

**Comment by dbrody** [comment]
Makes sense since keys are unique when pulling at the moment. So when pulling, it only grabs one. I'll make sure we look into that for the next major release.

Thanks!

**Comment by contentsync** [comment]
Update with ContentSync 6.1.1.

Now the setting is directly in the ContentSync pane.

![Screen Shot 2019-03-20 at 1 13 26 PM](https://user-images.githubusercontent.com/23665937/54716000-fcd73400-4b11-11e9-8935-d4c9c0f2011c.png)
