### ISSUE TITLE
Sketch crashes when using plugin with Abstract

### ISSUE THREAD

**Issue by creativechris08** [contentsync/SketchContentSync#93]
Does anyone know a fix for this please?

**Comment by dbrody** [comment]
Hi @creativechris08 , thanks for bringing this to my attention. Any chance you can provide more details? I'm having trouble replicating this.

**Comment by creativechris08** [comment]
Hi David,

Thanks for your reply, I’ll try get together a screen recording video at some point today. 

Thanks 🙏 

Sent from my iPhone 

Chris wood

**Comment by dbrody** [comment]
@creativechris08 - Let me know what you find. We've successfully been able to use this with Abstract on both Sketch 51 and 52.

**Comment by dzgnnl** [comment]
Head's up that I have been succesfully using it with Abstract 76.1.0.7501 / C

**Comment by contentsync** [comment]
Closing this as it is confirmed to work and have no current reports of issues. Any future issue please create a new issue item.
