### ISSUE TITLE
Feature Request: Add a link to toggle/ignore in content sycnh in the menu

### ISSUE THREAD

**Issue by keppes** [contentsync/SketchContentSync#94]
![screen shot 2018-10-05 at 11 22 23](https://user-images.githubusercontent.com/4143783/46527370-4ba94e00-c891-11e8-9628-de9d1317505f.png)
![screen shot 2018-10-05 at 11 25 08](https://user-images.githubusercontent.com/4143783/46527398-5fed4b00-c891-11e8-8f9e-fb8a70b005fd.png)

By adding a link for this functionality in the menu, you can create a custom short key.

-> also I could select multiple layers and apply this functionality to it, allowing me to work a lot faster and without the need of a GUI.

example: I select all layers by name by using another plugin or the layers list. I have assigned the command "ignore/show in content sync" a custom shortkey, like ctrl + shift + i. I apply the ignore functionality by applying this functionality on the selected layers. -> gain in efficiency = loss in time. Everybody happy, everybody dance

Keep up the great work (Jonas)

**Comment by dbrody** [comment]
@keppes - Great add. I'll update this thread as this feature progresses.

Thank you for the feature request and for using ContentSync.

Share the love and help us grow this community :) Tweet at and follow us on Twitter  [@contentsyncapp](https://twitter.com/contentsyncapp)!

**Comment by dbrody** [comment]
@keppes - This is now included in our recent update - ContentSync 5.1.

Here is a graphic showing the updated keyboard shortcuts:
![keyboard_shortcuts](https://user-images.githubusercontent.com/210322/46586413-ad94bf80-ca19-11e8-8d3a-c0a615b7ddbc.png)

Hope that helps!

**Comment by keppes** [comment]
Thanks, that was really fast! I'll gather my feedback in the coming days .

**Comment by dbrody** [comment]
Closing this issue as it has been resolved. ContentSync now includes this feature.
