### ISSUE TITLE
Feature request: Disable syncing of canvas optional

### ISSUE THREAD

**Issue by markgrahamdunn** [contentsync/SketchContentSync#95]
Would it be possible to disable the syncing of canvas (designs, visuals) per default and maybe have an toggle option to enable whenever it's needed?

**Comment by dbrody** [comment]
Can you elaborate more on the use cases where you see this feature being used? It will help evaluate the best way too approach this feature add.

Please address when you would like to sync the canvas and when you would rather not sync the canvas.
