### ISSUE TITLE
Compatibility with Sketch new version (54.1)

### ISSUE THREAD

**Issue by MattCowBoy** [contentsync/SketchContentSync#96]
Hi,
I've just tried ContentSync on the last version of sketch and it doesn't work.
Sketch crashes totally.
Do you have in plan any update?

Thank you so much

**Comment by dbrody** [comment]
@MattCowBoy  - ContentSync 6 is now released. It supports the latest Sketch 53 version and has a lot of exciting updates. I'm closing this issue but please open another if you keep experiencing problems.
