### ISSUE TITLE
Compatibility issues with OSX Mojave

### ISSUE THREAD

**Issue by kamicrafted** [contentsync/SketchContentSync#97]
The plugin doesn't seem to play nice with the latest version of OSX (10.14.1), currently using it with Sketch 52.4.

After several tries, I was able to finally get the ContentSync toolbar to display, following a restart of Sketch. However, elements are not visible on OSX's dark mode as the bar is light text on light background:

![image](https://user-images.githubusercontent.com/1197908/48784387-97348180-ecb0-11e8-9c08-c8f1331a5558.png)

I'm sure this wouldn't be on the highest priority but it'd be great for the plugin to work in dark mode. 

Awesome work and kudos to the team, thanks for putting out such a useful plugin!

**Comment by dbrody** [comment]
@kamicrafted - Yes, we are working on an update which will address this and more. Stay tuned - we will be releasing soon. Thanks!

**Comment by dbrody** [comment]
@kamicrafted - ContentSync 6 has been released which has a whole new inspector panel interface. It supports Sketch 53 and much more. Part of this is support for Dark Mode. It may require a Sketch restart but ContentSync now supports Dark Mode!
